services:

  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    volumes:
      - .:/app 

    expose:
      - "8000"
    depends_on:
      - db

  
  nginx:
    image: nginx:1.29.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles 
    depends_on:
      - web

 

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
